export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as VehicleCard } from './VehicleCard'
export { default as DealsCard } from './DealsCard'
export { default as SmallTouchBar} from './SmallTouchBar'
export { default as SignUp } from './SignUp'
export { default as SignIn } from './SignIn'
export { default as ForgotPassword } from './ForgotPassword'
export { default as ChangePassword } from './ChangePassword'
export { default as OTPVerification } from './OTPVerification'
export { default as CustomInput } from './CustomInput'
export { default as CustomButton } from './CustomButton' 
export { default as SocialIcon } from './SocialIcon' 