export { default as Home } from './Home'
export { default as Vehicles } from './Vehicles'
export { default as VehicleInfo } from './VehicleInfo'
export { default as Chat } from './Chat'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Auth } from './Auth'
export { default as ForgotPassword } from './ForgotPassword'